name: "standard"
description: "Standard workflow profile for general software development projects"
template: null
environment: "development"

default_stages:
  - "requirements_analysis"
  - "architecture_design"
  - "implementation_plan"
  - "code_generation"
  - "testing_setup"
  - "documentation"

stage_config:
  requirements_analysis:
    timeout: 300
    max_retries: 2
    agent_model: "claude-3-sonnet"
    enable_user_review: true
  
  architecture_design:
    timeout: 600
    max_retries: 3
    agent_model: "claude-3-opus"
    require_approval: true
  
  implementation_plan:
    timeout: 400
    max_retries: 2
    agent_model: "claude-3-sonnet"
    enable_dependencies: true
  
  code_generation:
    timeout: 1200
    max_retries: 3
    agent_model: "claude-3-opus"
    parallel_execution: false
    code_review_required: true
  
  testing_setup:
    timeout: 600
    max_retries: 2
    agent_model: "claude-3-sonnet"
    coverage_threshold: 80
  
  documentation:
    timeout: 400
    max_retries: 1
    agent_model: "claude-3-sonnet"
    auto_generate_readme: true

agent_config:
  temperature: 0.7
  max_tokens: 4000
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0

pause_points:
  - "requirements_analysis"
  - "architecture_design" 
  - "code_generation"

retry_config:
  max_stage_retries: 3
  backoff_multiplier: 2.0
  base_delay: 1.0
  jitter: true

notification_config:
  notify_on_completion: true
  notify_on_failure: true
  notify_on_pause: false
  email_recipients: []
  slack_channel: "#dev-workflows"

git_config:
  auto_commit: true
  auto_push: false
  branch_naming: "workflow/{project_name}_{timestamp}"
  commit_prefix: "feat"
  create_pr_on_completion: false

metadata:
  created_by: "system"
  version: "1.0.0"
  tags: ["standard", "development", "general"]
  suitable_for: ["web-apps", "apis", "libraries", "tools"]